In [1]:
import torch

In [2]:
x = torch.tensor([2], dtype=torch.float32, requires_grad=True)
y = 3 * x**3

In [4]:
y.backward()

In [5]:
x.grad

tensor([36.])

In [16]:
x1 = torch.tensor([4], dtype=torch.float32, requires_grad=True)
x2 = torch.tensor([2], dtype=torch.float32, requires_grad=True)

In [17]:
y = 2 * x1**2 + 3 * x2**3

In [18]:
y.backward()

In [19]:
x1.grad

tensor([16.])

In [20]:
x2.grad

tensor([36.])