In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
arr_t = torch.tensor([10])
arr_t

tensor([10])

In [4]:
arr_t.dtype

torch.int64

In [11]:
arr_t_f = torch.FloatTensor([10])
arr_t_f

tensor([10.])

In [12]:
arr_t_f.dtype

torch.float32

In [16]:
arr = np.arange(10)
arr_t_numpy = torch.from_numpy(arr)
arr_t_numpy

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])